# Generated by Django 5.2.1 on 2025-05-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('units', models.IntegerField()),
                ('property_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('payroll', models.FloatField()),
                ('marketing', models.FloatField()),
                ('admin', models.FloatField()),
                ('maintenance', models.FloatField()),
                ('turnover', models.FloatField()),
                ('utilities', models.FloatField()),
                ('taxes', models.FloatField()),
                ('insurance', models.FloatField()),
                ('management_fees', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.property')),
            ],
        ),
    ]
