# Generated by Django 5.2.1 on 2025-05-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_units_property_unit_count_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='unit_count',
            new_name='units',
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_entries', to='api.property'),
        ),
    ]
